apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-app-root
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:chapunchi/medium-argocd-gitops.git
    path: apps
    targetRevision: stg
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
